version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGODB_URI}  
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - .env  

  mongo:
    image: mongo:6
    ports:
      - "27019:27017"  
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network


volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
